language: cpp
compiler: gcc
dist: trusty
sudo: true

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt update -qq

install:
  # GCC
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # OpenMPI
  - sudo apt install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi-dev
  #- wget https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.0.tar.gz -O openmpi.tar.gz; tar zxf openmpi.tar.gz; cd openmpi*
  #- mkdir build; cd build
  #- ../configure
  #- sudo make all install
  #- cd ../..
  # wget
  - sudo apt install wget

script:
  - make -j
  # use standard sobol direction numbers
  - wget http://web.maths.unsw.edu.au/%7Efkuo/sobol/new-joe-kuo-6.21201 -O direction
  - ./example direction
  - mpirun -np 4 ./example direction

after_success:
  - echo "run test success"
 
after_failure:
  - echo "run test failure"
